spring:
  sql:
    init:
      mode:true
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization:
      true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect